# nome da pipeline
name: Run Basic Tests

# em que momento será executada
on: 
    pull_request:
        branches: [main]

jobs:
    # o que vai ser feito nessa pipeline
    # só teremos um job: rodar os testes
    cypress-run:
        # maquina que será executada
        runs-on: ubuntu-latest

        # passo a passo para rodar os testes
        steps:
            # clone do projeto
            - name: Checkout/Clone do projeto
              uses: actions/checkout@v4

            # exemplo de execução no terminal
            - name: instalar dependencias do projeto
              run: echo Humberto Dantas

            # execução e configuração do projeto
            - name: Run testes
              uses: cypress-io/github-actions@v6
              with:
                record: true
              env:
                CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
                  
